import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { Krn } from "../target/types/krn";
import { assert } from "chai";
import { ComputeBudgetProgram } from "@solana/web3.js";

describe("KRN SP1 zkTLS On-Chain Verification", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.krn as Program<Krn>;

  it("Verifies real SP1 zkTLS Groth16 proof on Solana devnet", async () => {
    // Real Groth16 proof generated by Succinct Prover Network
    // TLS connection to httpbin.org:443 verified inside SP1 zkVM
    const proofHex = "4388a21c0000000000000000000000000000000000000000000000000000000000000000002f850ee998974d6cc00e50cd0814b098c05bfade466d28573240d057f2535200000000000000000000000000000000000000000000000000000000000000002d76e6ea0cb77463de8472eda5f7ddf5708c9bd3f0efc5b1f87f9e0d8c597fcd0f444e762c947044a469b9ac71b7f7887bef0b6ef8259639c1488693545ad8d42d80cf0395ca97f5bb80ba7bf4e60bf89feec827284c3c5bf3f35a4124827f0a27ff13a3a9a66abbbd85100c3c56d5a21c93b9647a4691adadd8acb6c89b155918f370cace2dda4080ab96e4fafa0d7e68fa4aa6d96784fe8519550750c1a3b91d0b368027c7569d2525cec84fa3a5ed1b97f0ce3794b3170ddf3d727247c0891e3f54ae1d6fe07a19f43a06166401a2940a75776cce9c196d85e66426f831c1223c7ffa63785be749329cb7ec7a65cd3cba29345f753e9eb0aecb2892b29d87";

    const publicValuesHex = "018673e50f4a64071fdf70bf52b6fc39bdef98797d808fd61acce7dd8a3a461b86b262d5ef2b42600163a4dacb9b0eb17d3f7eb56c95222290dd7278aa3ddd389cc1e1d165cc4bafe5e19cb336d24b30c013e7bdb2e93659d6086672be7191a02262a7e032ceb43fc9000000000000000100";

    const proof = Buffer.from(proofHex, "hex");
    const publicValues = Buffer.from(publicValuesHex, "hex");

    console.log("Proof size:", proof.length, "bytes");
    console.log("Public values size:", publicValues.length, "bytes");
    console.log("Submitting SP1 zkTLS proof to Solana devnet...");

    const tx = await program.methods
      .verifySp1Zktls({
        proof: proof,
        publicValues: publicValues,
      })
      .accounts({
        caller: provider.wallet.publicKey,
      })
      .preInstructions([
        ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
      ])
      .rpc();

    console.log("\n=== SP1 zkTLS PROOF VERIFIED ON SOLANA DEVNET ===");
    console.log("Transaction:", tx);
    console.log("Explorer: https://explorer.solana.com/tx/" + tx + "?cluster=devnet");
    console.log("\nThis proves:");
    console.log("  - Real TLS connection to httpbin.org:443");
    console.log("  - Certificate chain verified against root CAs inside SP1 zkVM");
    console.log("  - Groth16 proof generated by Succinct Prover Network");
    console.log("  - Proof verified on-chain on Solana");
    console.log("  - No attestor. Mathematics only.");
  });
});
